General sign in endpoint and other small changes
Koervege/GruBack pull request #13
Opened 2021-03-23 22:16 UTC by Koervege

Changes:

-General sign in was implemented. This checks an incoming sign in http request and validates whether the info corresponds to a Client, a Supplier, or none. As a result, the specific sign in endpoints/controllers have been removed.
-The tokens generated for user authentication now encode the user type as well as the user's _id (e.g. whether an user is a Client or a Supplier).
-Removed the unnecessary requirement for the hour property in the Service model.
-The Service entity's creation controller now checks the user type from the token, rather than checking the user's type through a query.

2021-03-23 22:21 UTC, FernandoEspana approved these changes

2021-03-24 10:15 UTC, AlexisFranco approved these changes

2021-03-24 12:11 UTC, AlexisFranco approved these changes

2021-03-24 13:13 UTC, simonhoyos requested changes

2021-03-24 13:13 UTC, simonhoyos commented on src/controllers/user.controller.js
> +      }
Tener muchos condicionales y tener condiciones anidadas complican un poco el código. Te propongo esta alternativa para simplificar un poco este código

```javascript
const { email, password } = req.body

let validUser = await Client.findOne({ email })
// podemos decir de una vez que el tipo es cliente
let userType = 'client'

// este código solo se ejecuta si no encuentra un usuario
if(!validUser) {
  validUser = await Supplier.findOne({ email })
  // cambiamos el tipo de usuario
  userType = 'supplier'
}

// no necesitamos anidar condicionales. Sí no encuentra ninguno de los dos tipo lanzamos un error
if(!validUser) {
  throw Error('email o contraseña invalida')
}
```

2021-03-24 16:14 UTC, AlexisFranco requested changes

2021-03-24 16:14 UTC, AlexisFranco commented on src/controllers/user.controller.js
> +}
Carlos revisa porfa la identación

2021-03-24 17:22 UTC, Koervege commented on src/controllers/user.controller.js
> +      }
Gracias por la sugerencia. Ya lo cambié.

2021-03-24 17:23 UTC, Koervege commented on src/controllers/user.controller.js
> +}
Hecho.

2021-03-24 17:31 UTC, AlexisFranco approved these changes

2021-03-24 18:11 UTC, simonhoyos requested changes

2021-03-24 18:11 UTC, simonhoyos commented on src/controllers/user.controller.js
> +      let userType = 'client'
Prueba el código a ver si funciona. Creo que está línea te va a sacar un error por que la variable userType está siendo redeclarada. Ya se declaró en la línea 11

2021-03-24 21:10 UTC, Koervege commented on src/controllers/user.controller.js
> +      let userType = 'client'
Eso me pasa por hacer las cosas con afán. Corregido.

2021-03-24 21:46 UTC, simonhoyos approved these changes

2021-03-24 23:03 UTC, pipesoto13 approved these changes

2021-03-24 23:06 UTC, merged