Added support for image uploads
Koervege/GruBack pull request #15
Opened 2021-03-25 23:30 UTC by Koervege

-Cloudinary image upload middleware was created under the utils folder.
-An endpoint was added for image uploads for all entites except for services.

2021-03-26 00:12 UTC, FernandoEspana approved these changes

2021-03-26 11:46 UTC, simonhoyos requested changes

2021-03-26 11:46 UTC, simonhoyos commented on src/utils/formData.js
> +    req.body.photo = req.body.file.secure_url;
Revisa porfa la lógica de los controladores. Este middleware va a hacer que todos los documentos queden con las propiedades photo y file

2021-03-26 11:46 UTC, simonhoyos commented on src/utils/formData.js
> +    req.body.photo = req.body.file.secure_url;
Además esta lógica es muy especifica y asume que solo se envía un archivo y que el campo de ese archivo siempre es file. El nombre del campo puede cambiar según el append del formData en el FE

2021-03-26 18:47 UTC, simonhoyos approved these changes

2021-03-26 22:56 UTC, AlexisFranco approved these changes

2021-03-27 02:49 UTC, pipesoto13 approved these changes

2021-03-27 10:31 UTC, merged