Kubernetes backend
Koervege/GruBack pull request #17
Opened 2021-03-29 20:03 UTC by FernandoEspana

- Se creo archivo Docker.production para construir imagen de docker dentro de minikube
- Se incluyeron variables de entorno en archivo db.js y server.js para enlazar con las del archivo de deployment

2021-03-30 01:45 UTC, AlexisFranco approved these changes

2021-03-30 02:19 UTC, pipesoto13 approved these changes

2021-03-30 13:06 UTC, simonhoyos requested changes

2021-03-30 13:06 UTC, simonhoyos commented on deployment/database.yml
> +# kubectl exec -it gruappdatabasestatefulset-0 -c gruapp-database -- mongo --eval 'rs.initiate({ _id: "MainRepSet", version: 1, members: [ { _id: 0, host: "gruappdatabasestatefulset-0.gruappdatabases
No dejes estos comentarios acá tienen los accesos a la base de datos

2021-03-30 13:06 UTC, simonhoyos commented on deployment/frontend-service.yml
> +apiVersion: v1
movería los archivos que tienen que ver con el frontend al respositorio del frontend

2021-03-30 18:59 UTC, simonhoyos approved these changes

2021-03-31 14:44 UTC, Koervege approved these changes

2021-03-31 16:54 UTC, merged