User Authentication, validations and updated routes
Koervege/GruBack pull request #2
Opened 2021-03-12 18:03 UTC by AlexisFranco

Implemented the user validation, authentication with signup and signin controllers, utils folder with the auth.js file and updated de routes

2021-03-12 18:04 UTC, Koervege approved these changes

2021-03-12 19:11 UTC, simonhoyos requested changes

2021-03-12 19:11 UTC, simonhoyos commented on src/controllers/user.controller.js
> +		}
Ojo con la identación

2021-03-12 19:11 UTC, simonhoyos commented on src/models/user.model.js
> +	name: {
la identación de los archivos está quedando mezclada. En algunas partes está a dos espacios en otros está a 4

2021-03-12 19:11 UTC, simonhoyos commented on src/routes/user.js
> +router.route('/show').get(auth,show);
la información del usuario solo la puede ver el mismo usuario?

2021-03-12 19:11 UTC, simonhoyos commented on src/server.js
> +app.get('/', auth, (req, res) => {
Este endpoint no hace nada. Se puede borrar

2021-03-12 23:24 UTC, pipesoto13 approved these changes

2021-03-13 00:17 UTC, FernandoEspana approved these changes

2021-03-13 19:40 UTC, simonhoyos approved these changes

2021-03-13 19:52 UTC, merged