Tow model, controller and routes were created,also validations, auth …
Koervege/GruBack pull request #3
Opened 2021-03-13 21:31 UTC by FernandoEspana

…midlewares are pending

2021-03-14 01:04 UTC, simonhoyos requested changes
Los arreglos son pequeños. El PR en general está muy buebo

2021-03-14 01:04 UTC, simonhoyos commented on src/db.js
> +  mongoose.set('useFindAndModify', false);
Alguna razón para realizar esta configuración?

2021-03-14 01:04 UTC, simonhoyos commented on src/controllers/tow.controller.js
> +      const tow = await  Tow.create(body);
Ojo con la identación

2021-03-14 01:04 UTC, simonhoyos commented on src/controllers/tow.controller.js
> +      const { query } = req
Sí no están implementando filtros no es necesario pasar el query

2021-03-14 01:04 UTC, simonhoyos commented on src/controllers/tow.controller.js
> +      res.status(404).json({ message: 'ow not updated', tow});
Te falto un t en tow

2021-03-14 01:04 UTC, simonhoyos commented on src/controllers/tow.controller.js
> +const { update } = require('../models/tow.model');
Esta línea no es necesaria update no se está usando en este archivo

2021-03-14 02:47 UTC, FernandoEspana commented on src/db.js
> +  mongoose.set('useFindAndModify', false);
Hola Simón, bueno esa linea la puse ahí porque me arrojaba un warning, de todos modos la voy a quitar porque al ejecutar comentada linea ya no me arroja el warning.

2021-03-15 13:07 UTC, simonhoyos approved these changes

2021-03-15 13:20 UTC, AlexisFranco approved these changes

2021-03-15 13:26 UTC, pipesoto13 approved these changes

2021-03-15 15:16 UTC, Koervege approved these changes

2021-03-15 15:33 UTC, merged