Created the MVC of services
Koervege/GruBack pull request #4
Opened 2021-03-13 21:38 UTC by AlexisFranco

Create the model, controller, routes of the services and call from server.js

2021-03-13 22:37 UTC, FernandoEspana approved these changes

2021-03-14 00:02 UTC, pipesoto13 approved these changes

2021-03-14 01:09 UTC, simonhoyos requested changes
Veo que ya le estás cogiendo más el tiro al código del servidor. Me surgieron solo un par de dudas revisando el PR, las resolvemos y podemos hacer merge

2021-03-14 01:09 UTC, simonhoyos commented on src/controllers/service.controller.js
> +      const {query} = req;
Si no se están implementando filtros no es necesario pasar el query

2021-03-14 01:09 UTC, simonhoyos commented on src/models/service.model.js
> +const serviceSchema = new Schema({
Sería bueno agregar validaciones a los campos. A menos que los campos no lo requieran

2021-03-14 01:09 UTC, simonhoyos commented on src/routes/service.js
> +router.route('/').post(create);
Cualquier persona puede hacer estas peticiones?

2021-03-14 01:11 UTC, AlexisFranco commented on src/controllers/service.controller.js
> +      const {query} = req;
Dejé el query precisamente para poder hacer el filtro ya que no se está teniendo una ruta show por el momento

2021-03-14 01:12 UTC, AlexisFranco commented on src/models/service.model.js
> +const serviceSchema = new Schema({
Estas validaciones las pienso implementar después, sin embargo, si consideras que lo haga de una vez, lo hago.

2021-03-14 01:14 UTC, AlexisFranco commented on src/routes/service.js
> +router.route('/').post(create);
Las autorizaciones de acceso, están ligadas al usuario y al proveedor pero al igual que en el caso de los User de ayer (el controlador y ruta del show), pues se hará más adelante.

2021-03-15 12:33 UTC, Koervege approved these changes

2021-03-15 13:10 UTC, simonhoyos commented on src/controllers/service.controller.js
> +      const {query} = req;
súper, perfecto. Entonces ahí queda el query

2021-03-15 13:12 UTC, simonhoyos commented on src/models/service.model.js
> +const serviceSchema = new Schema({
Es mejor hacerlo de una vez. Esas deudas técnicas casi nunca se pagan. Después vas a tener que estar enfocado en otras tarea y el modelo seguramente se queda sin las validaciones

2021-03-15 13:12 UTC, simonhoyos commented on src/routes/service.js
> +router.route('/').post(create);
Perfecto

2021-03-15 15:19 UTC, AlexisFranco commented on src/models/service.model.js
> +const serviceSchema = new Schema({
Listo, pagué la deuda de una vez :P

2021-03-15 19:06 UTC, simonhoyos approved these changes

2021-03-15 19:29 UTC, merged