Created Model, Controllers and Routes for the Motorcycle Entity
Koervege/GruBack pull request #5
Opened 2021-03-15 16:11 UTC by Koervege

The following controllers were added:

create: creates a Motorcycle document for the current User and adds it to the User's references.
listUserBikes: lists all of the current User's bikes.
update: updates a given Motorcycle owned by current User.
destroy: deletes a given Motorcycle owned by current User.

All of the above require an authenticated jwt, which is validated with the already present auth.js in the utils folder.

2021-03-15 16:56 UTC, FernandoEspana commented on src/controllers/motorcycle.controller.js
> +    try {
Creo que hay que revisar la identacion bajo el bloque try

2021-03-15 16:56 UTC, FernandoEspana commented on src/controllers/motorcycle.controller.js
> +        res.status(400).json({ error, message: 'Something went wrong' });
Aqui tambien se fue la identacion mal

2021-03-15 18:43 UTC, FernandoEspana approved these changes

2021-03-15 19:18 UTC, simonhoyos requested changes

2021-03-15 19:18 UTC, simonhoyos commented on src/controllers/motorcycle.controller.js
> +      const fullUser = await User.findById(user);
Este renombramiento de la variable puede causar confusión. En un caso la invocas como userId en otro como user

2021-03-15 19:18 UTC, simonhoyos commented on src/controllers/motorcycle.controller.js
> +      }
Acá tienes que recorrer todos las motocicletas del un usuario para validar que ese usurio si es el dueño de la moto. Una alternativa puede ser buscar la moto por su id, validar que el usuario de asignado a esa moto sea el mismo usuario loggeado, y luego aplicar los cambios

2021-03-15 19:18 UTC, simonhoyos commented on src/controllers/motorcycle.controller.js
> +
Lo mismo que el comentario anterior. Y ojo con la identación

2021-03-15 19:18 UTC, simonhoyos commented on src/routes/motorcycle.js
> +router.route('/update').put(auth, update);
no es necesario que cada ruta tenga en el path el nombre del método que va a ejecutar. Recuerda un endpoint es una combinación de un método HTTP y una ruta. Ejemplo: `GET /` es diferente de `POST /` que a su vez es diferente de `PUT /`

2021-03-15 19:18 UTC, simonhoyos commented on src/models/motorcycle.model.js
> +    type: [{ type: Schema.Types.ObjectId, ref: 'Service' }],
Ojo con la identación

2021-03-15 19:18 UTC, simonhoyos commented on src/models/motorcycle.model.js
> +    plateNum: {
Sería bueno agregar la expresión regular que agregaron en el módelo de gruas

2021-03-16 00:17 UTC, AlexisFranco approved these changes

2021-03-16 12:53 UTC, simonhoyos approved these changes

2021-03-16 13:33 UTC, pipesoto13 approved these changes

2021-03-16 13:34 UTC, merged