Supplier models, controller and routes
Koervege/GruBack pull request #6
Opened 2021-03-16 00:45 UTC by pipesoto13

2021-03-16 00:57 UTC, AlexisFranco approved these changes

2021-03-16 13:05 UTC, simonhoyos approved these changes

2021-03-16 13:05 UTC, simonhoyos commented on src/controllers/supplier.controller.js
> +      const {
Es buena idea validar que el que el supplier que estamos intentando borrar sea el mismo que el usuario autenticado. No queremos que cualquier persona pueda ir por ahí borrando cualquier Supplier

2021-03-16 13:05 UTC, simonhoyos commented on src/controllers/supplier.controller.js
> +  async update(req, res) {
Lo mismo que el controlador destroy

2021-03-16 13:06 UTC, simonhoyos requested changes
El status anterior me equivoque. Hay cositas por cambiar

2021-03-16 13:29 UTC, Koervege approved these changes

2021-03-16 13:40 UTC, FernandoEspana approved these changes

2021-03-17 04:17 UTC, pipesoto13 commented on src/controllers/supplier.controller.js
> +  async update(req, res) {
Al usar la autenticación con token ya queda validado que el proveedor que está borrando o editando la grúa es la misma persona.

2021-03-17 13:03 UTC, simonhoyos commented on src/controllers/supplier.controller.js
> +  async update(req, res) {
No necesariamente, al usar el middleware de autenticación estamos validando que el usuario tiene una sesión activa y no que sea el dueño del perfil, moto, grúa, servicio, etc.

2021-03-17 13:28 UTC, pipesoto13 reviewed
hecho

2021-03-17 17:11 UTC, simonhoyos approved these changes

2021-03-17 17:16 UTC, merged