References of services
Koervege/GruBack pull request #9
Opened 2021-03-18 17:29 UTC by AlexisFranco

- Created the references services to tows and motorcycles.

- Fixed bugs to auth and motorcycles controller

2021-03-18 18:55 UTC, simonhoyos requested changes

2021-03-18 18:55 UTC, simonhoyos commented on src/controllers/service.controller.js
> +        const service = await (await Service.create(body));
No es necesario tener esos 2 awaits. Con uno es suficiente

2021-03-18 18:55 UTC, simonhoyos commented on src/controllers/service.controller.js
> +      }
Si ya existe un token, y pasamos por el middleware de auth quiere decir que el usuario ya es está registrado y que esta loggeado en la aplicación

2021-03-18 19:32 UTC, pipesoto13 approved these changes

2021-03-18 23:55 UTC, FernandoEspana approved these changes

2021-03-19 13:30 UTC, AlexisFranco commented on src/controllers/service.controller.js
> +      }
Nosotros en la aplicación tenemos 2 usuarios diferentes, uno para el cliente y uno para el proveedor, esta validación que hago es porque el único que debe crear servicios es el usuario y de esta manera, fue que encontré como hacerlo

2021-03-19 13:30 UTC, AlexisFranco commented on src/controllers/service.controller.js
> +        const service = await (await Service.create(body));
Los puse para hacer la verificación de que exista primero la motocicleta, si no existe pues arroja un error, si existe prosigue con la validación de la grúa. O te refieres a que esta validación se puede hacer en un solo await?

2021-03-19 18:46 UTC, simonhoyos approved these changes

2021-03-19 19:27 UTC, Koervege approved these changes

2021-03-19 19:27 UTC, Koervege commented on src/controllers/service.controller.js
> +        const service = await (await Service.create(body));
Por qué el doble await?

2021-03-19 19:27 UTC, Koervege commented on src/controllers/service.controller.js
> +      }
A lo que @AlexisFranco  se refiere aquí, es que solo el usuario motociclista (que es un 'User') puede crear/hacer una petición de servicio. los usuarios de Grúa ('Supplier') se autentican igual, pero no deben poder crear un servicio.

2021-03-19 19:28 UTC, merged

2021-03-19 19:32 UTC, AlexisFranco commented on src/controllers/service.controller.js
> +        const service = await (await Service.create(body));
Error mío, pero ya quedó arreglado :)